### ISSUE TITLE
Set up Prefect 

### ISSUE THREAD

**Issue by Idrissben** [Idrissben/xhec-mlops-JIMAMS#4]
- Use the prefect library to adapt the code developed in the PR2 to use flow and task objects
- Files to be modified: the src/modelling folder

 Don't forget to update the requirements.in file with the new dependencies (and compile it to generate the requirements.txt file)
 Don't forget to update the README.md file with the new steps to reproduce to run the code
 You should among other add instructions to run the prefect UI and visualize the flow runs

**Comment by Sarelim** [comment]
Done (Branch 3 merged)
